export const GET_SUB_CATS_IN_PROGRESS = 'GET_SUB_CATS_IN_PROGRESS';
export const GET_SUB_CATS_SUCCESS = 'GET_SUB_CATS_SUCCESS';
export const GET_SUB_CATS_FAILURE = 'GET_SUB_CATS_FAILURE';

export const GET_ORGS_SUB_CATS_IN_PROGRESS = 'GET_ORGS_SUB_CATS_IN_PROGRESS';
export const GET_ORGS_SUB_CATS_SUCCESS = 'GET_ORGS_SUB_CATS_SUCCESS';
export const GET_ORGS_SUB_CATS_FAILURE = 'GET_ORGS_SUB_CATS_FAILURE';

export const GET_ORGS_IN_PROGRESS = 'GET_ORGS_IN_PROGRESS';
export const GET_ORGS_SUCCESS = 'GET_ORGS_SUCCESS';
export const GET_ORGS_FAILURE = 'GET_ORGS_FAILURE';

export const GET_CATS_IN_PROGRESS = 'GET_CATS_IN_PROGRESS';
export const GET_CATS_SUCCESS = 'GET_CATS_SUCCESS';
export const GET_CATS_FAILURE = 'GET_CATS_FAILURE';

export const POST_ORG_IN_PROGRESS = 'POST_ORG_IN_PROGRESS';
export const POST_ORG_SUCCESS = 'POST_ORG_SUCCESS';
export const POST_ORG_BAD = 'POST_ORG_BAD';
export const POST_ORG_FAILURE = 'POST_ORG_FAILURE';
